import "react-toastify/dist/ReactToastify.css";
import "./main.css";

export const metadata = {
  title: "Fintech.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
